ALTER TABLE users
    ALTER COLUMN full_name DROP NOT NULL,
    ALTER COLUMN email DROP NOT NULL,
    ALTER COLUMN password_hash DROP NOT NULL,
    ALTER COLUMN visa_type DROP NOT NULL,
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE account_deletion_audit (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    deleted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    purge_version INTEGER NOT NULL
);
